---
parsl_log_level: WARNING
default_threads: 4
ModelEvaluation:
  cores_per_worker: 4
  gpu: True
  max_simulation_time: 0.4
ModelTraining:
  cores_per_worker: 4
  gpu: true
  max_training_time: 1
  max_workers: 1
CP2K:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  launch_command: 'apptainer exec -e --no-init oras://ghcr.io/molmod/cp2k:2023.2 /opt/entry.sh mpirun -np 2 -x OMP_NUM_THREADS=1 cp2k.psmp -i cp2k.inp'
...
